/*******************************************************************************
 * Copyright 2026 Microchip FPGA Embedded Systems Solutions.
 *
 * SPDX-License-Identifier: MIT
 *
 * @file core_qse.c
 * @author Microchip FPGA Embedded Systems Solutions
 * @brief CoreQSE bare metal driver implementation.
 *
 * API names follow coreqse-driver-user-guide.md.
 * Register behaviour follows CoreQSE User Guide DS50004157A, register
 * specification 2.0.101.
 *
 * See file "core_qse.h" for a description of the functions implemented here.
 */

#include "coreqse_reg_map_regs.h"
#include "core_qse.h"
#include "coreqse_user_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Null parameters with appropriate type definitions.
 */
#define NULL_INSTANCE               (( QSE_instance_t * ) 0)
#define NULL_TX_CONFIG              (( QSE_tx_config_t * ) 0)
#define NULL_RX_CONFIG              (( QSE_rx_config_t * ) 0)
#define NULL_PAUSE_CONFIG           (( QSE_pause_config_t * ) 0)
#define NULL_TX_STATS               (( QSE_tx_stats_t * ) 0)
#define NULL_RX_STATS               (( QSE_rx_stats_t * ) 0)
#define NULL_U8                     (( uint8_t * ) 0)
#define NULL_U16                    (( uint16_t * ) 0)
#define NULL_U32                    (( uint32_t * ) 0)
#define NULL_CONST_U8               (( const uint8_t * ) 0)

#define DISABLE                     ( 0u )
#define ENABLE                      ( 1u )

/*******************************************************************************
 * Local constants.
 */
#define QSE_MAC_ADDR_LEN            ( 6u )
#define QSE_ETH_HDR_LEN             ( 14u )
#define QSE_FCS_LEN                 ( 4u )
#define QSE_PAD_TO_LEN              ( 60u )
#define QSE_VER_RESERVED_MASK       ( 0x0000FFFFuL )
#define QSE_BROADCAST_BYTE          ( 0xFFu )
#define QSE_BYTE_MASK               ( 0xFFu )
#define QSE_BYTE_SHIFT              ( 8u )
#define QSE_NO_FAILED_OFFSET        ( 0xFFFFFFFFuL )
#define QSE_PREAMBLE_SIZE_DEFAULT   ( 0u )
#define QSE_LINK_SETTLE_LOOPS       ( 100000u )

/*******************************************************************************
 * Reset values checked by QSE_self_test().
 */
#define QSE_RESET_MAC_TX_CFG        COREQSE_REG_MAP_MAC_TX_CFG_REG_RESET_VALUE
#define QSE_RESET_MAC_RX_CFG        COREQSE_REG_MAP_MAC_RX_CFG_REG_RESET_VALUE

/*******************************************************************************
 * MAC_ADDR_UPPER byte placement.
 *
 * User guide DS50004157A section 6.68 describes MAC_ADDR_UPPER as the "MAC
 * address upper 16 bits" and lists:
 *     Bits 15:8 - MAC ADDR BYTE 5[7:0]   MAC address upper 16 bits [15:8]
 *     Bits 15:8 - MAC ADDR BYTE 4[7:0]   MAC address upper 16 bits [7:0]
 *
 * The second entry repeats "Bits 15:8" but its description says "[7:0]", so
 * byte 4 occupies bits 7:0 and byte 5 occupies bits 15:8. That is the layout
 * used here.
 *
 * The autogenerated header inherits the same typo: it defines both
 * MAC_ADDR_UPPER_MAC_ADDR_BYTE_4_SHIFT and _BYTE_5_SHIFT as 8, and its
 * REG_RW_MASK of 0x0001FE00 describes an 8-bit field at bit 9 rather than the
 * 16-bit field two address bytes require. The generated shifts are therefore
 * not used. Verify with QSE_set_mac_addr() followed by QSE_get_mac_addr()
 * before relying on unicast filtering.
 */
#define QSE_MAC_ADDR_BYTE4_SHIFT    ( 0u )
#define QSE_MAC_ADDR_BYTE5_SHIFT    ( 8u )

/*******************************************************************************
 * Helpers for building register fields from the autogenerated shift and
 * no-shift mask definitions.
 */
#define QSE_FIELD( REG, FIELD, VALUE )                                        \
    ( ( ( (uint32_t)(VALUE) ) &                                               \
        COREQSE_REG_MAP_##REG##_##FIELD##_NS_MASK )                           \
      << COREQSE_REG_MAP_##REG##_##FIELD##_SHIFT )

#define QSE_MASK( REG, FIELD )                                                \
    ( ( (uint32_t)COREQSE_REG_MAP_##REG##_##FIELD##_NS_MASK )                 \
      << COREQSE_REG_MAP_##REG##_##FIELD##_SHIFT )

/*******************************************************************************
 * QSE_init()
 */
uint8_t
QSE_init
(
    QSE_instance_t * this_qse,
    addr_t           base_addr
)
{
    uint8_t status = QSE_ERR_PARAM;
    uint8_t idx;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( base_addr != 0u );

    if( ( this_qse != NULL_INSTANCE ) && ( base_addr != 0u ) )
    {
        this_qse->base_address = base_addr;

        for( idx = 0u; idx < QSE_MAC_ADDR_LEN; idx++ )
        {
            this_qse->mac_addr[ idx ] = 0u;
        }

        /* No PHY is associated until QSE_attach_mdio() is called. Designs with
         * no PHY, such as the 2.5 Gbps SMA loopback design, never call it, and
         * the QSE_phy_* functions then report QSE_ERR_NOT_SUPPORTED rather than
         * appearing to succeed.
         */
        this_qse->mdio_base_address = 0u;
        this_qse->phy_addr          = 0u;

        /* Cache the current configuration so later read-modify-write operations
         * preserve fields this driver does not own.
         */
        this_qse->tx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_TX_CFG );

        this_qse->rx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_RX_CFG );

        /* Both enable bits are set at reset, so the MAC is already running.
         * Quiesce it so that configuration is applied cleanly.
         */
        this_qse->tx_cfg_shadow &= ~QSE_MASK( MAC_TX_CFG, MAC_TX_EN );
        this_qse->rx_cfg_shadow &= ~QSE_MASK( MAC_RX_CFG, MAC_RX_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_TX_CFG,
                           this_qse->tx_cfg_shadow );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_CFG,
                           this_qse->rx_cfg_shadow );

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_default_tx_cfg()
 */
uint8_t
QSE_get_default_tx_cfg
(
    QSE_tx_config_t * cfg
)
{
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( cfg != NULL_TX_CONFIG );

    if( cfg != NULL_TX_CONFIG )
    {
        cfg->fcs_insert_mode  = ENABLE;
        cfg->fcs_stomp_mode   = DISABLE;
        cfg->fcs_error_inject = DISABLE;

        /* The user guide states MAC_TX_PAD_EN is only valid when
         * MAC_TX_FCS_INS is clear. The default inserts the FCS, so padding
         * must default off; the MAC enforces the minimum frame size itself.
         */
        cfg->pad_enable       = DISABLE;

        cfg->ipg_count        = QSE_IPG_CNT_STANDARD;
        cfg->max_tx_pkt_len   = COREQSE_FRAME_LEN_MAX;

        /* Standard preamble. The custom preamble requires an optional block, so
         * leaving this at zero keeps the defaults valid on every IP build.
         */
        cfg->preamble_size    = QSE_PREAMBLE_SIZE_DEFAULT;
        cfg->preamble_content = 0u;

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_default_rx_cfg()
 */
uint8_t
QSE_get_default_rx_cfg
(
    QSE_rx_config_t * cfg
)
{
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( cfg != NULL_RX_CONFIG );

    if( cfg != NULL_RX_CONFIG )
    {
        /* Strip the FCS so software sees payload only. */
        cfg->fcs_remove     = ENABLE;
        cfg->pad_remove     = DISABLE;
        cfg->max_rx_pkt_len = COREQSE_FRAME_LEN_MAX;
        cfg->preamble_size  = QSE_PREAMBLE_SIZE_DEFAULT;

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_tx_cfg_set()
 */
uint8_t
QSE_tx_cfg_set
(
    QSE_instance_t        * this_qse,
    const QSE_tx_config_t * cfg
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t reg_value;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( cfg != NULL_TX_CONFIG );

    if( ( this_qse != NULL_INSTANCE ) && ( cfg != NULL_TX_CONFIG ) &&
        ( cfg->ipg_count >= QSE_IPG_CNT_MIN ) &&
        ( cfg->ipg_count <= QSE_IPG_CNT_MAX ) &&
        ( cfg->preamble_size <= QSE_PREAMBLE_SIZE_MAX ) &&
        ( cfg->max_tx_pkt_len != 0u ) )
    {
        status = QSE_OK;

#if ( COREQSE_CFG_TX_PREAMBLE == 0u )
        /* The custom preamble block was not generated, so a non-default
         * preamble size would silently have no effect.
         */
        if( cfg->preamble_size != QSE_PREAMBLE_SIZE_DEFAULT )
        {
            status = QSE_ERR_NOT_SUPPORTED;
        }
#endif

        if( status == QSE_OK )
        {
            /* Preserve the transmit enable state. */
            reg_value = this_qse->tx_cfg_shadow &
                        QSE_MASK( MAC_TX_CFG, MAC_TX_EN );

            reg_value |= QSE_FIELD( MAC_TX_CFG, MAC_TX_IFG_CNT,
                                    cfg->ipg_count );

            reg_value |= QSE_FIELD( MAC_TX_CFG, MAC_TX_MAX_PKT_LEN,
                                    cfg->max_tx_pkt_len );

            if( cfg->fcs_stomp_mode != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_TX_CFG, MAC_TX_FCS_STOMP );
            }

            if( cfg->fcs_error_inject != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_TX_CFG, MAC_TX_FCS_ERR );
            }

            if( cfg->fcs_insert_mode != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_TX_CFG, MAC_TX_FCS_INS );
            }

            if( cfg->pad_enable != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_TX_CFG, MAC_TX_PAD_EN );
            }

            /* MAC_TX_PREAMBLE_EN selects the custom preamble, which is only
             * meaningful when a size was requested.
             */
            if( cfg->preamble_size != QSE_PREAMBLE_SIZE_DEFAULT )
            {
                reg_value |= QSE_MASK( MAC_TX_CFG, MAC_TX_PREAMBLE_EN );
            }

            reg_value |= QSE_FIELD( MAC_TX_CFG, MAC_TX_PREAMBLE_WCM1,
                                    cfg->preamble_size );

            HAL_set_32bit_reg( this_qse->base_address,
                               COREQSE_REG_MAP_MAC_TX_CFG, reg_value );

            this_qse->tx_cfg_shadow = reg_value;

#if ( COREQSE_CFG_TX_PREAMBLE != 0u )
            if( cfg->preamble_size != QSE_PREAMBLE_SIZE_DEFAULT )
            {
                HAL_set_32bit_reg( this_qse->base_address,
                                   COREQSE_REG_MAP_MAC_TX_PRE_LOWER,
                                   cfg->preamble_content );
            }
#endif
        }
    }

    return ( status );
}

/*******************************************************************************
 * QSE_rx_cfg_set()
 */
uint8_t
QSE_rx_cfg_set
(
    QSE_instance_t        * this_qse,
    const QSE_rx_config_t * cfg
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t reg_value;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( cfg != NULL_RX_CONFIG );

    if( ( this_qse != NULL_INSTANCE ) && ( cfg != NULL_RX_CONFIG ) &&
        ( cfg->preamble_size <= QSE_PREAMBLE_SIZE_MAX ) &&
        ( cfg->max_rx_pkt_len != 0u ) &&
        /* MAC_RX_PAD_REMOVAL is only valid when MAC_RX_FCS_REMOVE is set. */
        ( ( cfg->pad_remove == DISABLE ) || ( cfg->fcs_remove != DISABLE ) ) )
    {
        status = QSE_OK;

#if ( COREQSE_CFG_RX_PREAMBLE == 0u )
        if( cfg->preamble_size != QSE_PREAMBLE_SIZE_DEFAULT )
        {
            status = QSE_ERR_NOT_SUPPORTED;
        }
#endif

        if( status == QSE_OK )
        {
            /* Preserve the receive enable state and the Wake-on-LAN bit, which
             * is owned by QSE_wol_enable() and QSE_wol_disable().
             */
            reg_value = this_qse->rx_cfg_shadow &
                        ( QSE_MASK( MAC_RX_CFG, MAC_RX_EN ) |
                          QSE_MASK( MAC_RX_CFG, WOL_EN ) );

            if( cfg->pad_remove != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_RX_CFG, MAC_RX_PAD_REMOVAL );
            }

            if( cfg->fcs_remove != DISABLE )
            {
                reg_value |= QSE_MASK( MAC_RX_CFG, MAC_RX_FCS_RMV );
            }

            reg_value |= QSE_FIELD( MAC_RX_CFG, MAC_RX_MAX_PKT_LEN,
                                    cfg->max_rx_pkt_len );

            reg_value |= QSE_FIELD( MAC_RX_CFG, MAC_RX_PREAMBLE_WCM1,
                                    cfg->preamble_size );

            HAL_set_32bit_reg( this_qse->base_address,
                               COREQSE_REG_MAP_MAC_RX_CFG, reg_value );

            this_qse->rx_cfg_shadow = reg_value;
        }
    }

    return ( status );
}

/*******************************************************************************
 * QSE_set_mac_addr()
 */
uint8_t
QSE_set_mac_addr
(
    QSE_instance_t * this_qse,
    const uint8_t  * mac_addr
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t lower;
    uint32_t upper;
    uint8_t  idx;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( mac_addr != NULL_CONST_U8 );

    if( ( this_qse != NULL_INSTANCE ) && ( mac_addr != NULL_CONST_U8 ) )
    {
        /* Bytes 0 to 3, byte 0 first on the wire. */
        lower = QSE_FIELD( MAC_ADDR_LOWER, MAC_ADDR_BYTE_0, mac_addr[ 0u ] ) |
                QSE_FIELD( MAC_ADDR_LOWER, MAC_ADDR_BYTE_1, mac_addr[ 1u ] ) |
                QSE_FIELD( MAC_ADDR_LOWER, MAC_ADDR_BYTE_2, mac_addr[ 2u ] ) |
                QSE_FIELD( MAC_ADDR_LOWER, MAC_ADDR_BYTE_3, mac_addr[ 3u ] );

        /* Bytes 4 and 5. See the QSE_MAC_ADDR_BYTE4_SHIFT comment above. */
        upper = ( ( (uint32_t)mac_addr[ 4u ] & QSE_BYTE_MASK )
                    << QSE_MAC_ADDR_BYTE4_SHIFT ) |
                ( ( (uint32_t)mac_addr[ 5u ] & QSE_BYTE_MASK )
                    << QSE_MAC_ADDR_BYTE5_SHIFT );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_ADDR_LOWER, lower );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_ADDR_UPPER, upper );

        for( idx = 0u; idx < QSE_MAC_ADDR_LEN; idx++ )
        {
            this_qse->mac_addr[ idx ] = mac_addr[ idx ];
        }

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_mac_addr()
 */
uint8_t
QSE_get_mac_addr
(
    const QSE_instance_t * this_qse,
    uint8_t              * mac_addr
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t lower;
    uint32_t upper;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( mac_addr != NULL_U8 );

    if( ( this_qse != NULL_INSTANCE ) && ( mac_addr != NULL_U8 ) )
    {
        lower = HAL_get_32bit_reg( this_qse->base_address,
                                   COREQSE_REG_MAP_MAC_ADDR_LOWER );

        upper = HAL_get_32bit_reg( this_qse->base_address,
                                   COREQSE_REG_MAP_MAC_ADDR_UPPER );

        mac_addr[ 0u ] = (uint8_t)
            ( ( lower >> COREQSE_REG_MAP_MAC_ADDR_LOWER_MAC_ADDR_BYTE_0_SHIFT )
              & QSE_BYTE_MASK );
        mac_addr[ 1u ] = (uint8_t)
            ( ( lower >> COREQSE_REG_MAP_MAC_ADDR_LOWER_MAC_ADDR_BYTE_1_SHIFT )
              & QSE_BYTE_MASK );
        mac_addr[ 2u ] = (uint8_t)
            ( ( lower >> COREQSE_REG_MAP_MAC_ADDR_LOWER_MAC_ADDR_BYTE_2_SHIFT )
              & QSE_BYTE_MASK );
        mac_addr[ 3u ] = (uint8_t)
            ( ( lower >> COREQSE_REG_MAP_MAC_ADDR_LOWER_MAC_ADDR_BYTE_3_SHIFT )
              & QSE_BYTE_MASK );
        mac_addr[ 4u ] = (uint8_t)
            ( ( upper >> QSE_MAC_ADDR_BYTE4_SHIFT ) & QSE_BYTE_MASK );
        mac_addr[ 5u ] = (uint8_t)
            ( ( upper >> QSE_MAC_ADDR_BYTE5_SHIFT ) & QSE_BYTE_MASK );

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_wire_length()
 */
uint8_t
QSE_get_wire_length
(
    const QSE_instance_t * this_qse,
    uint16_t               payload_len,
    uint16_t             * wire_len,
    uint16_t             * rx_len
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t tx_cfg;
    uint32_t rx_cfg;
    uint16_t len;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( payload_len != 0u );

    if( ( this_qse != NULL_INSTANCE ) && ( payload_len != 0u ) )
    {
        tx_cfg = HAL_get_32bit_reg( this_qse->base_address,
                                    COREQSE_REG_MAP_MAC_TX_CFG );

        rx_cfg = HAL_get_32bit_reg( this_qse->base_address,
                                    COREQSE_REG_MAP_MAC_RX_CFG );

        len = payload_len;

        /* The MAC pads frames whose payload is shorter than 46 bytes, giving a
         * 60-byte frame before any FCS. This happens either when
         * MAC_TX_PAD_EN is set, or when MAC_TX_FCS_INS is set and the MAC
         * therefore owns the frame tail.
         */
        if( ( ( ( tx_cfg & QSE_MASK( MAC_TX_CFG, MAC_TX_PAD_EN  ) ) != 0u ) ||
              ( ( tx_cfg & QSE_MASK( MAC_TX_CFG, MAC_TX_FCS_INS ) ) != 0u ) ) &&
            ( len < QSE_PAD_TO_LEN ) )
        {
            len = QSE_PAD_TO_LEN;
        }

        /* The FCS is appended after padding. */
        if( ( tx_cfg & QSE_MASK( MAC_TX_CFG, MAC_TX_FCS_INS ) ) != 0u )
        {
            len = (uint16_t)( len + QSE_FCS_LEN );
        }

        if( wire_len != NULL_U16 )
        {
            *wire_len = len;
        }

        if( rx_len != NULL_U16 )
        {
            /* The receiver optionally strips the FCS before the frame reaches
             * AXI4-Stream, reducing the length the DMA must be armed for.
             */
            if( ( ( rx_cfg & QSE_MASK( MAC_RX_CFG, MAC_RX_FCS_RMV ) ) != 0u ) &&
                ( len >= QSE_FCS_LEN ) )
            {
                *rx_len = (uint16_t)( len - QSE_FCS_LEN );
            }
            else
            {
                *rx_len = len;
            }
        }

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_tx_enable()
 */
void
QSE_tx_enable
(
    QSE_instance_t * this_qse
)
{
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->tx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_TX_CFG );

        this_qse->tx_cfg_shadow |= QSE_MASK( MAC_TX_CFG, MAC_TX_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_TX_CFG,
                           this_qse->tx_cfg_shadow );
    }
}

/*******************************************************************************
 * QSE_tx_disable()
 */
void
QSE_tx_disable
(
    QSE_instance_t * this_qse
)
{
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->tx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_TX_CFG );

        this_qse->tx_cfg_shadow &= ~QSE_MASK( MAC_TX_CFG, MAC_TX_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_TX_CFG,
                           this_qse->tx_cfg_shadow );
    }
}

/*******************************************************************************
 * QSE_rx_enable()
 */
void
QSE_rx_enable
(
    QSE_instance_t * this_qse
)
{
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->rx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_RX_CFG );

        this_qse->rx_cfg_shadow |= QSE_MASK( MAC_RX_CFG, MAC_RX_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_CFG,
                           this_qse->rx_cfg_shadow );
    }
}

/*******************************************************************************
 * QSE_rx_disable()
 */
void
QSE_rx_disable
(
    QSE_instance_t * this_qse
)
{
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->rx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_RX_CFG );

        this_qse->rx_cfg_shadow &= ~QSE_MASK( MAC_RX_CFG, MAC_RX_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_CFG,
                           this_qse->rx_cfg_shadow );
    }
}

/*******************************************************************************
 * QSE_tx_frame()
 *
 * Not implementable: CoreQSE has no processor addressable transmit data path.
 * See the description in core_qse.h.
 */
uint8_t
QSE_tx_frame
(
    QSE_instance_t * this_qse,
    const uint8_t  * frame_data,
    uint32_t         frame_len
)
{
    ( void ) this_qse;
    ( void ) frame_data;
    ( void ) frame_len;

    return ( QSE_ERR_NOT_SUPPORTED );
}

/*******************************************************************************
 * QSE_get_tx_status()
 *
 * CoreQSE has no transmit status register. SYS_MAC_TX_ERR_FIFO_UNDERRUN is a
 * hardware output port only. The best available substitute is the transmit
 * error counter, when the statistics block exists.
 */
uint8_t
QSE_get_tx_status
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_STATS == 0u )
    ( void ) this_qse;

    return ( 0u );
#else
    uint8_t  status = 0u;
    uint32_t tx_err;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        tx_err = HAL_get_32bit_reg( this_qse->base_address,
                                    COREQSE_REG_MAP_MAC_TX_ERR );

        if( tx_err != 0u )
        {
            status = 1u;
        }
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_get_rx_status()
 *
 * CoreQSE has no receive status register. SYS_MAC_RX_FIFO_OVERFLOW is a
 * hardware output port only.
 */
uint8_t
QSE_get_rx_status
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_STATS == 0u )
    ( void ) this_qse;

    return ( 0u );
#else
    uint8_t  status = 0u;
    uint32_t rx_err;
    uint32_t rx_drop;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        rx_err = HAL_get_32bit_reg( this_qse->base_address,
                                    COREQSE_REG_MAP_MAC_RX_ERR );

        rx_drop = HAL_get_32bit_reg( this_qse->base_address,
                                     COREQSE_REG_MAP_MAC_RX_DROP );

        if( ( rx_err != 0u ) || ( rx_drop != 0u ) )
        {
            status = 1u;
        }
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_pcs_get_sync_status()
 *
 * CoreQSE has no PCS status register. The SYNC and PCS_RX_SYNC_FSM_CUR_STATE
 * outputs are hardware ports only. This samples the PCS error counters twice
 * and reports stability, which is an indirect indication.
 */
uint8_t
QSE_pcs_get_sync_status
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_STATS == 0u )
    ( void ) this_qse;

    /* No software visible link indication exists in this build. */
    return ( 0u );
#else
    uint8_t           status = 0u;
    uint32_t          code_first;
    uint32_t          sync_first;
    uint32_t          code_second;
    uint32_t          sync_second;
    volatile uint32_t loop;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        code_first = HAL_get_32bit_reg( this_qse->base_address,
                                        COREQSE_REG_MAP_PCS_CODE_ERR );
        sync_first = HAL_get_32bit_reg( this_qse->base_address,
                                        COREQSE_REG_MAP_PCS_SYNC_LOST_ERR );

        for( loop = 0u; loop < QSE_LINK_SETTLE_LOOPS; loop++ )
        {
            /* Allow any instability to accumulate in the counters. */
        }

        code_second = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_PCS_CODE_ERR );
        sync_second = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_PCS_SYNC_LOST_ERR );

        if( ( code_second == code_first ) && ( sync_second == sync_first ) )
        {
            status = 1u;
        }
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_self_test()
 */
uint8_t
QSE_self_test
(
    const QSE_instance_t * this_qse,
    uint32_t             * failed_offset
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t reg_value;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        status = QSE_OK;

        if( failed_offset != NULL_U32 )
        {
            *failed_offset = QSE_NO_FAILED_OFFSET;
        }

        /* CORE_VER bits [15:0] are reserved and must read as zero. */
        reg_value = HAL_get_32bit_reg( this_qse->base_address,
                                       COREQSE_REG_MAP_CORE_VER );

        if( ( reg_value & QSE_VER_RESERVED_MASK ) != 0u )
        {
            if( failed_offset != NULL_U32 )
            {
                *failed_offset = COREQSE_REG_MAP_CORE_VER_REG_OFFSET;
            }
            status = QSE_ERR;
        }

        /* MAC_TX_CFG reset value, ignoring MAC_TX_EN which QSE_init() clears
         * and which may legitimately be toggled at run time.
         */
        if( status == QSE_OK )
        {
            reg_value = HAL_get_32bit_reg( this_qse->base_address,
                                           COREQSE_REG_MAP_MAC_TX_CFG );

            if( ( reg_value & ~QSE_MASK( MAC_TX_CFG, MAC_TX_EN ) ) !=
                ( QSE_RESET_MAC_TX_CFG
                              & ~QSE_MASK( MAC_TX_CFG, MAC_TX_EN ) ) )
            {
                if( failed_offset != NULL_U32 )
                {
                    *failed_offset = COREQSE_REG_MAP_MAC_TX_CFG_REG_OFFSET;
                }
                status = QSE_ERR;
            }
        }

        /* MAC_RX_CFG reset value, ignoring MAC_RX_EN. */
        if( status == QSE_OK )
        {
            reg_value = HAL_get_32bit_reg( this_qse->base_address,
                                           COREQSE_REG_MAP_MAC_RX_CFG );

            if( ( reg_value & ~QSE_MASK( MAC_RX_CFG, MAC_RX_EN ) ) !=
                ( QSE_RESET_MAC_RX_CFG
                              & ~QSE_MASK( MAC_RX_CFG, MAC_RX_EN ) ) )
            {
                if( failed_offset != NULL_U32 )
                {
                    *failed_offset = COREQSE_REG_MAP_MAC_RX_CFG_REG_OFFSET;
                }
                status = QSE_ERR;
            }
        }

        /* MAC_TX_PARAM1/2 and MAC_RX_PARAM1/2 are deliberately not checked.
         * They are read-only registers reporting the build-time configuration:
         *
         *   MAC_xX_PARAM2 = { 11'b0, PAUSE_EN, ECC_ENABLE, CHECK_LT,
         *                     PREAMBLE, RAM_TYPE, FIFO_MODE, FIFO_DEPTH }
         *
         * Their value depends on the IP configurator settings, so no constant
         * comparison is valid. The user guide's "Reset: 0x20" holds only for a
         * build with RAM_TYPE 0; an LSRAM build reads 0x00010020.
         */
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_version()
 */
uint8_t
QSE_get_version
(
    const QSE_instance_t * this_qse,
    uint8_t              * major,
    uint8_t              * minor
)
{
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t reg_value;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        reg_value = HAL_get_32bit_reg( this_qse->base_address,
                                       COREQSE_REG_MAP_CORE_VER );

        if( major != NULL_U8 )
        {
            *major = (uint8_t)
                ( ( reg_value >> COREQSE_REG_MAP_CORE_VER_MAJOR_VER_SHIFT ) &
                  COREQSE_REG_MAP_CORE_VER_MAJOR_VER_NS_MASK );
        }

        if( minor != NULL_U8 )
        {
            *minor = (uint8_t)
                ( ( reg_value >> COREQSE_REG_MAP_CORE_VER_MINOR_VER_SHIFT ) &
                  COREQSE_REG_MAP_CORE_VER_MINOR_VER_NS_MASK );
        }

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_tx_param()
 */
uint8_t
QSE_get_tx_param
(
    const QSE_instance_t * this_qse,
    uint32_t             * param1,
    uint32_t             * param2
)
{
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        if( param1 != NULL_U32 )
        {
            *param1 = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_MAC_TX_PARAM1 );
        }

        if( param2 != NULL_U32 )
        {
            *param2 = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_MAC_TX_PARAM2 );
        }

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_get_rx_param()
 */
uint8_t
QSE_get_rx_param
(
    const QSE_instance_t * this_qse,
    uint32_t             * param1,
    uint32_t             * param2
)
{
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        if( param1 != NULL_U32 )
        {
            *param1 = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_MAC_RX_PARAM1 );
        }

        if( param2 != NULL_U32 )
        {
            *param2 = HAL_get_32bit_reg( this_qse->base_address,
                                         COREQSE_REG_MAP_MAC_RX_PARAM2 );
        }

        status = QSE_OK;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_pause_cfg_set()
 */
uint8_t
QSE_pause_cfg_set
(
    QSE_instance_t           * this_qse,
    const QSE_pause_config_t * cfg
)
{
#if ( ( COREQSE_CFG_RX_PAUSE == 0u ) && ( COREQSE_CFG_TX_PAUSE == 0u ) )
    ( void ) this_qse;
    ( void ) cfg;

    return ( QSE_ERR_NOT_SUPPORTED );
#else
    uint8_t  status = QSE_ERR_PARAM;
    uint32_t reg_value;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( cfg != NULL_PAUSE_CONFIG );

    if( ( this_qse != NULL_INSTANCE ) && ( cfg != NULL_PAUSE_CONFIG ) &&
        ( cfg->rx_fifo_low_watermark  <= QSE_PAUSE_WATERMARK_MAX ) &&
        ( cfg->rx_fifo_high_watermark <= QSE_PAUSE_WATERMARK_MAX ) &&
        ( cfg->rx_fifo_high_watermark >  cfg->rx_fifo_low_watermark ) )
    {
        status = QSE_OK;

#if ( COREQSE_CFG_RX_PAUSE != 0u )
        reg_value = QSE_FIELD( MAC_RX_PAUSE_WM, MAC_RX_PAUSE_LWM,
                               cfg->rx_fifo_low_watermark ) |
                    QSE_FIELD( MAC_RX_PAUSE_WM, MAC_RX_PAUSE_HWM,
                               cfg->rx_fifo_high_watermark );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_PAUSE_WM, reg_value );

        reg_value = QSE_FIELD( MAC_RX_PAUSE_RTX, MAC_RX_PAUSE_RETRANSMISSION,
                               cfg->pause_quanta_retransmit );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_PAUSE_RTX, reg_value );
#endif

#if ( COREQSE_CFG_TX_PAUSE != 0u )
        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_TX_PAUSE_TMR,
                           QSE_FIELD( MAC_TX_PAUSE_TMR, MAC_TX_PAUSE_TMR,
                                      cfg->pause_timer ) );
#endif
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_set_rx_filter_pkt_cfg()
 *
 * A set bit DROPS frames matching that condition. See core_qse.h.
 */
uint8_t
QSE_set_rx_filter_pkt_cfg
(
    QSE_instance_t * this_qse,
    uint32_t         filter_mask
)
{
#if ( COREQSE_CFG_RX_FRMFIL_PKT == 0u )
    ( void ) this_qse;
    ( void ) filter_mask;

    /* The frame filter block was not generated: all frames are accepted and
     * writing the register would have no effect.
     */
    return ( QSE_ERR_NOT_SUPPORTED );
#else
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_FRMFIL_PKT, filter_mask );

        status = QSE_OK;
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_get_rx_filter_pkt_cfg()
 */
uint8_t
QSE_get_rx_filter_pkt_cfg
(
    const QSE_instance_t * this_qse,
    uint32_t             * filter_mask
)
{
#if ( COREQSE_CFG_RX_FRMFIL_PKT == 0u )
    ( void ) this_qse;
    ( void ) filter_mask;

    return ( QSE_ERR_NOT_SUPPORTED );
#else
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( filter_mask != NULL_U32 );

    if( ( this_qse != NULL_INSTANCE ) && ( filter_mask != NULL_U32 ) )
    {
        *filter_mask = HAL_get_32bit_reg( this_qse->base_address,
                                     COREQSE_REG_MAP_MAC_RX_FRMFIL_PKT );

        status = QSE_OK;
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_set_rx_filter_hash()
 */
uint8_t
QSE_set_rx_filter_hash
(
    QSE_instance_t * this_qse,
    uint32_t         hash_table_low,
    uint32_t         hash_table_high
)
{
#if ( COREQSE_CFG_RX_FRMFIL_HASH == 0u )
    ( void ) this_qse;
    ( void ) hash_table_low;
    ( void ) hash_table_high;

    return ( QSE_ERR_NOT_SUPPORTED );
#else
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_FRMFIL_HTR0,
                           hash_table_low );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_FRMFIL_HTR1,
                           hash_table_high );

        status = QSE_OK;
    }

    return ( status );
#endif
}

/*******************************************************************************
 * QSE_wol_enable()
 */
void
QSE_wol_enable
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_RX_WOL == 0u )
    ( void ) this_qse;
#else
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->rx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_RX_CFG );

        this_qse->rx_cfg_shadow |= QSE_MASK( MAC_RX_CFG, WOL_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_CFG,
                           this_qse->rx_cfg_shadow );
    }
#endif
}

/*******************************************************************************
 * QSE_wol_disable()
 */
void
QSE_wol_disable
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_RX_WOL == 0u )
    ( void ) this_qse;
#else
    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        this_qse->rx_cfg_shadow = HAL_get_32bit_reg( this_qse->base_address,
                                              COREQSE_REG_MAP_MAC_RX_CFG );

        this_qse->rx_cfg_shadow &= ~QSE_MASK( MAC_RX_CFG, WOL_EN );

        HAL_set_32bit_reg( this_qse->base_address,
                           COREQSE_REG_MAP_MAC_RX_CFG,
                           this_qse->rx_cfg_shadow );
    }
#endif
}

/*******************************************************************************
 * QSE_get_tx_stats()
 *
 * Reads are NON-DESTRUCTIVE: the counters are Read/Write-to-Clear (RWC) in
 * hardware, not read-to-clear as the driver user guide states.
 */
void
QSE_get_tx_stats
(
    QSE_instance_t * this_qse,
    QSE_tx_stats_t * stats_out
)
{
#if ( COREQSE_CFG_STATS == 0u )
    uint32_t * p;
    uint32_t   i;

    ( void ) this_qse;

    /* The counter block was not generated. Zero the structure so the caller
     * sees a defined result, but note that all-zero is indistinguishable from
     * a healthy idle link: check COREQSE_CFG_STATS before relying on it.
     */
    if( stats_out != NULL_TX_STATS )
    {
        p = (uint32_t *)stats_out;
        for( i = 0u; i < ( sizeof(QSE_tx_stats_t) / sizeof(uint32_t) ); i++ )
        {
            p[ i ] = 0u;
        }
    }
#else
    addr_t base;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( stats_out != NULL_TX_STATS );

    if( ( this_qse != NULL_INSTANCE ) && ( stats_out != NULL_TX_STATS ) )
    {
        base = this_qse->base_address;

        stats_out->tx_frame_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PKT );
        stats_out->tx_err_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_ERR );
        stats_out->tx_length_long_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LL_ERR );
        stats_out->tx_length_check_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LC_ERR );
        stats_out->tx_length_short_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LS_ERR );
        stats_out->tx_fcs_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FCS_ERR );
        stats_out->tx_frame_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FRM_ERR );
        stats_out->tx_broadcast_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_BCAST );
        stats_out->tx_multicast_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MCAST );
        stats_out->tx_pause_frame_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PF );
        stats_out->tx_control_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_CF );
        stats_out->tx_vlan_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_VLAN );
        stats_out->tx_pad_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PAD );
        stats_out->tx_64b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_64B );
        stats_out->tx_127b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_127B );
        stats_out->tx_255b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_255B );
        stats_out->tx_511b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_511B );
        stats_out->tx_1kb_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_1KB );
        stats_out->tx_maxb_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MAXB );
        stats_out->tx_maxb_vlan_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MAXB_VLAN );
        stats_out->tx_oversize_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_GTMAXB );
        stats_out->tx_fifo_ecc_sb_corr =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FIFO_SBCOR );
        stats_out->tx_fifo_ecc_db_det =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FIFO_DBDET );
    }
#endif
}

/*******************************************************************************
 * QSE_get_rx_stats()
 */
void
QSE_get_rx_stats
(
    QSE_instance_t * this_qse,
    QSE_rx_stats_t * stats_out
)
{
#if ( COREQSE_CFG_STATS == 0u )
    uint32_t * p;
    uint32_t   i;

    ( void ) this_qse;

    if( stats_out != NULL_RX_STATS )
    {
        p = (uint32_t *)stats_out;
        for( i = 0u; i < ( sizeof(QSE_rx_stats_t) / sizeof(uint32_t) ); i++ )
        {
            p[ i ] = 0u;
        }
    }
#else
    addr_t base;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( stats_out != NULL_RX_STATS );

    if( ( this_qse != NULL_INSTANCE ) && ( stats_out != NULL_RX_STATS ) )
    {
        base = this_qse->base_address;

        stats_out->rx_frame_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PKT );
        stats_out->rx_err_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_ERR );
        stats_out->rx_length_long_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LL_ERR );
        stats_out->rx_length_check_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LC_ERR );
        stats_out->rx_length_short_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LS_ERR );
        stats_out->rx_fcs_error_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FCS_ERR );
        stats_out->rx_frame_err =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FRM_ERR );
        stats_out->rx_broadcast_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_BCAST );
        stats_out->rx_multicast_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MCAST );
        stats_out->rx_pause_frame_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PF );
        stats_out->rx_control_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_CF );
        stats_out->rx_vlan_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_VLAN );
        stats_out->rx_pad_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PAD );
        stats_out->rx_64b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_64B );
        stats_out->rx_127b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_127B );
        stats_out->rx_255b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_255B );
        stats_out->rx_511b_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_511B );
        stats_out->rx_1kb_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_1KB );
        stats_out->rx_maxb_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MAXB );
        stats_out->rx_maxb_vlan_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MAXB_VLAN );
        stats_out->rx_oversize_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_GTMAXB );
        stats_out->rx_fifo_ecc_sb_corr =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FIFO_SBCOR );
        stats_out->rx_fifo_ecc_db_det =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FIFO_DBDET );
        stats_out->rx_drop_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_DROP );

        stats_out->pcs_eb_ecc_sb_corr =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_PCS_EB_SBCOR );
        stats_out->pcs_eb_ecc_db_det =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_PCS_EB_DBDET );
        stats_out->pcs_code_err_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_PCS_CODE_ERR );
        stats_out->pcs_sync_lost_count =
            HAL_get_32bit_reg( base, COREQSE_REG_MAP_PCS_SYNC_LOST_ERR );
    }
#endif
}

/*******************************************************************************
 * QSE_clear_stats()
 *
 * The counters are Read/Write-to-Clear, so this WRITES each register. The
 * driver user guide describes clearing by reading, which would leave every
 * counter unchanged on this hardware.
 */
void
QSE_clear_stats
(
    QSE_instance_t * this_qse
)
{
#if ( COREQSE_CFG_STATS == 0u )
    ( void ) this_qse;
#else
    addr_t         base;
    const uint32_t clr = 0xFFFFFFFFuL;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse != NULL_INSTANCE )
    {
        base = this_qse->base_address;

        /* Transmit counters. */
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PKT,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_ERR,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LL_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LC_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_LS_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FCS_ERR,    clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FRM_ERR,    clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_BCAST,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MCAST,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PF,         clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_CF,         clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_VLAN,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_PAD,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_64B,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_127B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_255B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_511B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_1KB,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MAXB,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_MAXB_VLAN,  clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_GTMAXB,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FIFO_SBCOR, clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_TX_FIFO_DBDET, clr );

        /* Receive counters. */
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PKT,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_ERR,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LL_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LC_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_LS_ERR,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FCS_ERR,    clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FRM_ERR,    clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_BCAST,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MCAST,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PF,         clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_CF,         clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_VLAN,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_PAD,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_64B,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_127B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_255B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_511B,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_1KB,        clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MAXB,       clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_MAXB_VLAN,  clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_GTMAXB,     clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FIFO_SBCOR, clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_FIFO_DBDET, clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_MAC_RX_DROP,       clr );

        /* PCS counters. */
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_PCS_EB_SBCOR,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_PCS_EB_DBDET,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_PCS_CODE_ERR,      clr );
        HAL_set_32bit_reg( base, COREQSE_REG_MAP_PCS_SYNC_LOST_ERR, clr );
    }
#endif
}

/*******************************************************************************
 * QSE_stats_are_clean()
 */
uint8_t
QSE_stats_are_clean
(
    const QSE_rx_stats_t * before,
    const QSE_rx_stats_t * after
)
{
    uint8_t status = QSE_ERR_PARAM;

    HAL_ASSERT( before != (const QSE_rx_stats_t *)0 );
    HAL_ASSERT( after  != (const QSE_rx_stats_t *)0 );

    if( ( before != (const QSE_rx_stats_t *)0 ) &&
        ( after  != (const QSE_rx_stats_t *)0 ) )
    {
        status = QSE_OK;

        if( ( after->rx_err_count        != before->rx_err_count        ) ||
            ( after->rx_length_long_err  != before->rx_length_long_err  ) ||
            ( after->rx_length_check_err != before->rx_length_check_err ) ||
            ( after->rx_length_short_err != before->rx_length_short_err ) ||
            ( after->rx_fcs_error_count  != before->rx_fcs_error_count  ) ||
            ( after->rx_frame_err        != before->rx_frame_err        ) ||
            ( after->rx_oversize_count   != before->rx_oversize_count   ) ||
            ( after->rx_drop_count       != before->rx_drop_count       ) )
        {
            status = QSE_ERR;
        }

        if( ( after->rx_fifo_ecc_sb_corr != before->rx_fifo_ecc_sb_corr ) ||
            ( after->rx_fifo_ecc_db_det  != before->rx_fifo_ecc_db_det  ) ||
            ( after->pcs_eb_ecc_sb_corr  != before->pcs_eb_ecc_sb_corr  ) ||
            ( after->pcs_eb_ecc_db_det   != before->pcs_eb_ecc_db_det   ) )
        {
            status = QSE_ERR;
        }

        /* The only available indication that the receive path lost alignment. */
        if( ( after->pcs_code_err_count  != before->pcs_code_err_count  ) ||
            ( after->pcs_sync_lost_count != before->pcs_sync_lost_count ) )
        {
            status = QSE_ERR;
        }
    }

    return ( status );
}

/*******************************************************************************
 * QSE_build_frame_header()
 */
uint16_t
QSE_build_frame_header
(
    uint8_t              * buffer,
    const uint8_t        * dest_mac,
    const uint8_t        * src_mac,
    uint16_t               ether_type,
    const QSE_instance_t * this_qse
)
{
    uint16_t bytes_written = 0u;
    uint8_t  idx;

    HAL_ASSERT( buffer != NULL_U8 );

    /* A source address is required either explicitly or via the instance. */
    if( ( buffer != NULL_U8 ) &&
        ( ( src_mac != NULL_CONST_U8 ) || ( this_qse != NULL_INSTANCE ) ) )
    {
        for( idx = 0u; idx < QSE_MAC_ADDR_LEN; idx++ )
        {
            if( dest_mac != NULL_CONST_U8 )
            {
                buffer[ idx ] = dest_mac[ idx ];
            }
            else
            {
                buffer[ idx ] = QSE_BROADCAST_BYTE;
            }
        }

        for( idx = 0u; idx < QSE_MAC_ADDR_LEN; idx++ )
        {
            if( src_mac != NULL_CONST_U8 )
            {
                buffer[ QSE_MAC_ADDR_LEN + idx ] = src_mac[ idx ];
            }
            else
            {
                buffer[ QSE_MAC_ADDR_LEN + idx ] = this_qse->mac_addr[ idx ];
            }
        }

        /* EtherType, most significant byte first on the wire. */
        buffer[ 12u ] = (uint8_t)( ( ether_type >> QSE_BYTE_SHIFT ) &
                                   QSE_BYTE_MASK );
        buffer[ 13u ] = (uint8_t)( ether_type & QSE_BYTE_MASK );

        bytes_written = QSE_ETH_HDR_LEN;
    }

    return ( bytes_written );
}

/*==============================================================================
 *              EXTERNAL PHY MANAGEMENT, MDIO / MII STATION
 *
 * These functions present PHY management as part of the CoreQSE API, in the
 * style of the CoreTSE driver, but CoreQSE contains NO MII management hardware.
 * Every function here delegates to core_mdio.c, which drives the separate
 * COREMDIO_APB IP. See the architectural note in core_qse.h.
 *
 * Each function builds a temporary MDIO_instance_t from the base address stored
 * by QSE_attach_mdio(). That keeps the CoreQSE instance self contained: the
 * application holds one object rather than two, which is the point of the
 * exercise.
 *============================================================================*/

/*! Build the transport instance from what QSE_attach_mdio() recorded. */
#define QSE_MDIO_FROM( QSE )    { ( QSE )->mdio_base_address }

/*! Translate an MDIO_* status into the QSE_* status space. */
static uint8_t qse_map_mdio_status( uint8_t mdio_status )
{
    uint8_t status;

    switch( mdio_status )
    {
        case MDIO_OK:
            status = QSE_OK;
            break;

        case MDIO_ERR_PARAM:
            status = QSE_ERR_PARAM;
            break;

        case MDIO_ERR_NO_PHY:
        case MDIO_ERR_CONSTANT:
        case MDIO_ERR_TIMEOUT:
        default:
            status = QSE_ERR;
            break;
    }

    return ( status );
}

/*******************************************************************************
 * QSE_attach_mdio()
 */
uint8_t
QSE_attach_mdio
(
    QSE_instance_t * this_qse,
    addr_t           mdio_base_addr,
    uint8_t          phy_addr,
    uint32_t         mdio_prescaler
)
{
    uint8_t         status = QSE_ERR_PARAM;
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );
    HAL_ASSERT( mdio_base_addr != 0u );
    HAL_ASSERT( phy_addr <= 31u );

    if( ( this_qse != NULL_INSTANCE ) && ( mdio_base_addr != 0u ) &&
        ( phy_addr <= 31u ) )
    {
        this_qse->mdio_base_address = mdio_base_addr;
        this_qse->phy_addr          = phy_addr;

        /* Initialize the transport. MDIO_init() also clamps the prescaler to a
         * value the IP actually decodes and clears the control register, so a
         * stale direction bit from a previous run cannot corrupt the first read.
         */
        status = qse_map_mdio_status(
                     MDIO_init( &mdio, mdio_base_addr, mdio_prescaler ) );
    }

    return ( status );
}

/*******************************************************************************
 * QSE_read_phy_reg()
 */
uint8_t
QSE_read_phy_reg
(
    const QSE_instance_t * this_qse,
    uint8_t                reg_addr,
    uint16_t             * data
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( ( this_qse == NULL_INSTANCE ) || ( data == NULL_U16 ) )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( qse_map_mdio_status(
                 MDIO_read( &mdio, this_qse->phy_addr, reg_addr, data ) ) );
}

/*******************************************************************************
 * QSE_write_phy_reg()
 */
uint8_t
QSE_write_phy_reg
(
    const QSE_instance_t * this_qse,
    uint8_t                reg_addr,
    uint16_t               data
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( qse_map_mdio_status(
                 MDIO_write( &mdio, this_qse->phy_addr, reg_addr, data ) ) );
}

/*******************************************************************************
 * QSE_phy_verify_mdio()
 */
uint8_t
QSE_phy_verify_mdio
(
    const QSE_instance_t * this_qse,
    uint16_t               readings[4]
)
{
    MDIO_instance_t mdio;
    uint8_t         mdio_status;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    mdio_status = MDIO_self_test( &mdio, this_qse->phy_addr, readings );

    /* MDIO_ERR_CONSTANT and MDIO_ERR_NO_PHY both mean the readings cannot be
     * trusted, so both map to QSE_ERR. The caller can call MDIO_self_test()
     * directly if it needs to distinguish them, as the test application does in
     * order to print a specific diagnosis.
     */
    return ( qse_map_mdio_status( mdio_status ) );
}

/*******************************************************************************
 * QSE_phy_get_id()
 */
uint8_t
QSE_phy_get_id
(
    const QSE_instance_t * this_qse,
    uint32_t             * phy_id
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( ( this_qse == NULL_INSTANCE ) || ( phy_id == NULL_U32 ) )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( qse_map_mdio_status(
                 MDIO_get_phy_id( &mdio, this_qse->phy_addr, phy_id ) ) );
}

/*******************************************************************************
 * QSE_phy_init()
 */
uint8_t
QSE_phy_init
(
    const QSE_instance_t * this_qse
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    /* Dispatches to the compiled PHY implementation. This example ships
     * null_phy.c, a generic IEEE Clause 22 driver. See phy.h if a vendor
     * specific implementation is required.
     */
    return ( qse_map_mdio_status( PHY_init( &mdio, this_qse->phy_addr ) ) );
}

/*******************************************************************************
 * QSE_phy_set_link_speed()
 */
uint8_t
QSE_phy_set_link_speed
(
    const QSE_instance_t * this_qse,
    uint32_t               speed_duplex_select
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( qse_map_mdio_status(
                 PHY_set_link_speed( &mdio, this_qse->phy_addr,
                                     speed_duplex_select ) ) );
}

/*******************************************************************************
 * QSE_phy_autonegotiate()
 */
uint8_t
QSE_phy_autonegotiate
(
    const QSE_instance_t * this_qse,
    uint32_t               wait_ms,
    MDIO_link_progress_t   progress_cb
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( QSE_ERR_PARAM );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        return ( QSE_ERR_NOT_SUPPORTED );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( qse_map_mdio_status(
                 PHY_autonegotiate( &mdio, this_qse->phy_addr, wait_ms,
                                    progress_cb ) ) );
}

/*******************************************************************************
 * QSE_phy_get_link_status()
 */
uint8_t
QSE_phy_get_link_status
(
    const QSE_instance_t * this_qse,
    PHY_speed_t          * speed,
    uint8_t              * fullduplex
)
{
    MDIO_instance_t mdio;

    HAL_ASSERT( this_qse != NULL_INSTANCE );

    if( this_qse == NULL_INSTANCE )
    {
        return ( PHY_LINK_DOWN );
    }

    if( this_qse->mdio_base_address == 0u )
    {
        /* No PHY in this design. Link state must be inferred from the PCS
         * counters using QSE_pcs_get_sync_status() instead.
         */
        if( speed != (PHY_speed_t *)0 )
        {
            *speed = PHY_SPEED_INVALID;
        }
        return ( PHY_LINK_DOWN );
    }

    mdio.base_address = this_qse->mdio_base_address;

    return ( PHY_get_link_status( &mdio, this_qse->phy_addr, speed,
                                  fullduplex ) );
}

/*******************************************************************************
 * QSE_phy_get_name()
 */
const char *
QSE_phy_get_name( void )
{
    return ( PHY_get_name() );
}

#ifdef __cplusplus
}
#endif
