/***************************************************************************************************
 * Copyright 2026 Microchip FPGA Embedded Systems Solutions.
 * Script version: develop-1.0.022
 * Register specification version: 2.0.101
 * Register specification Date: August 04, 12:30, 2026
 * Note: Autogenerated headers from IP supplied xlsx
 * Author: Embedded Software
 */ 

#ifndef COREQSE_REG_MAP_TYPES_H_
#define COREQSE_REG_MAP_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __I
#define __I  const volatile
#endif

#ifndef __O
#define __O  volatile
#endif

#ifndef __IO
#define __IO volatile
#endif

typedef struct
{
	__I uint32_t CORE_VER; /* 0x0 */
	__I uint32_t MAC_TX_PARAM1; /* 0x4 */
	__I uint32_t MAC_TX_PARAM2; /* 0x8 */
	__I uint32_t MAC_RX_PARAM1; /* 0xc */
	__I uint32_t MAC_RX_PARAM2; /* 0x10 */
	 uint32_t reserved1[3];/* 0x14 */	__IO uint32_t MAC_ADDR_UPPER; /* 0x20 */
	__IO uint32_t MAC_ADDR_LOWER; /* 0x24 */
	 uint32_t reserved2[54];/* 0x28 */	__IO uint32_t MAC_TX_CFG; /* 0x100 */
	__IO uint32_t MAC_TX_PRE_UPPER; /* 0x104 */
	__IO uint32_t MAC_TX_PRE_LOWER; /* 0x108 */
	 uint32_t reserved3[25];/* 0x10c */	__IO uint32_t MAC_TX_PAUSE_TIMER; /* 0x170 */
	 uint32_t reserved4[3];/* 0x174 */	__IO uint32_t MAC_RX_CFG; /* 0x180 */
	 uint32_t reserved5[3];/* 0x184 */	__IO uint32_t MAC_RX_FRMFIL_PKT; /* 0x190 */
	 uint32_t reserved6[3];/* 0x194 */	__IO uint32_t MAC_RX_FRMFIL_HTR0; /* 0x1a0 */
	__IO uint32_t MAC_RX_FRMFIL_HTR1; /* 0x1a4 */
	 uint32_t reserved7[18];/* 0x1a8 */	__IO uint32_t MAC_RX_PAUSE_WM; /* 0x1f0 */
	__IO uint32_t MAC_RX_PAUSE_RTX; /* 0x1f4 */
	 uint32_t reserved8[2];/* 0x1f8 */	__IO uint32_t MAC_TX_PKT; /* 0x200 */
	__IO uint32_t MAC_TX_ERR; /* 0x204 */
	__IO uint32_t MAC_TX_LL_ERR; /* 0x208 */
	__IO uint32_t MAC_TX_LC_ERR; /* 0x20c */
	__IO uint32_t MAC_TX_LS_ERR; /* 0x210 */
	__IO uint32_t MAC_TX_FCS_ERR; /* 0x214 */
	__IO uint32_t MAC_TX_FRM_ERR; /* 0x218 */
	__IO uint32_t MAC_TX_BCAST; /* 0x21c */
	__IO uint32_t MAC_TX_MCAST; /* 0x220 */
	__IO uint32_t MAC_TX_PF; /* 0x224 */
	__IO uint32_t MAC_TX_CF; /* 0x228 */
	__IO uint32_t MAC_TX_VLAN; /* 0x22c */
	__IO uint32_t MAC_TX_PAD; /* 0x230 */
	__IO uint32_t MAC_TX_64B; /* 0x234 */
	__IO uint32_t MAC_TX_127B; /* 0x238 */
	__IO uint32_t MAC_TX_255B; /* 0x23c */
	__IO uint32_t MAC_TX_511B; /* 0x240 */
	__IO uint32_t MAC_TX_1KB; /* 0x244 */
	__IO uint32_t MAC_TX_MAXB; /* 0x248 */
	__IO uint32_t MAC_TX_MAXB_VLAN; /* 0x24c */
	__IO uint32_t MAC_TX_GTMAXB; /* 0x250 */
	 uint32_t reserved9[2];/* 0x254 */	__IO uint32_t MAC_TX_FIFO_SBCOR; /* 0x25c */
	__IO uint32_t MAC_TX_FIFO_DBDET; /* 0x260 */
	 uint32_t reserved10[103];/* 0x264 */	__IO uint32_t MAC_RX_PKT; /* 0x400 */
	__IO uint32_t MAC_RX_ERR; /* 0x404 */
	__IO uint32_t MAC_RX_LL_ERR; /* 0x408 */
	__IO uint32_t MAC_RX_LC_ERR; /* 0x40c */
	__IO uint32_t MAC_RX_LS_ERR; /* 0x410 */
	__IO uint32_t MAC_RX_FCS_ERR; /* 0x414 */
	__IO uint32_t MAC_RX_FRM_ERR; /* 0x418 */
	__IO uint32_t MAC_RX_BCAST; /* 0x41c */
	__IO uint32_t MAC_RX_MCAST; /* 0x420 */
	__IO uint32_t MAC_RX_PF; /* 0x424 */
	__IO uint32_t MAC_RX_CF; /* 0x428 */
	__IO uint32_t MAC_RX_VLAN; /* 0x42c */
	__IO uint32_t MAC_RX_PAD; /* 0x430 */
	__IO uint32_t MAC_RX_64B; /* 0x434 */
	__IO uint32_t MAC_RX_127B; /* 0x438 */
	__IO uint32_t MAC_RX_255B; /* 0x43c */
	__IO uint32_t MAC_RX_511B; /* 0x440 */
	__IO uint32_t MAC_RX_1KB; /* 0x444 */
	__IO uint32_t MAC_RX_MAXB; /* 0x448 */
	__IO uint32_t MAC_RX_MAXB_VLAN; /* 0x44c */
	__IO uint32_t MAC_RX_GTMAXB; /* 0x450 */
	 uint32_t reserved11[2];/* 0x454 */	__IO uint32_t MAC_RX_FIFO_SBCOR; /* 0x45c */
	__IO uint32_t MAC_RX_FIFO_DBDET; /* 0x460 */
	__IO uint32_t MAC_RX_DROP; /* 0x464 */
	 uint32_t reserved12[38];/* 0x468 */	__IO uint32_t PCS_EB_SBCOR; /* 0x500 */
	__IO uint32_t PCS_EB_DBDET; /* 0x504 */
	__IO uint32_t PCS_CODE_ERR; /* 0x508 */
	__IO uint32_t PCS_SYNC_LOST_ERR; /* 0x50c */

 } CoreQSE_Reg_Map_TypeDef;



#ifdef __cplusplus
}
#endif

#endif /* COREQSE_REG_MAP_TYPES_H_ */